[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_app = "5gdV4b4cPnnRkVSvBq8WxCxRfyq7i5z9R5scwm3BA4ps"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
